config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get 'users/profile/:id' => 'users#profile', as: 'profile'

  get 'users/repository/' => 'users#repository', as: 'repository'

  get 'user/new'

  get "/auth/:provider/callback" => "sessions#create"

  get "/signout" => "sessions#destroy", as: :signout

end

app/models/user.rb
class User < ActiveRecord::Base
	def self.create_with_omniauth(auth)
	    create! do |user|
	      user.provider = auth["provider"]
	      user.uid = auth["uid"]
	      user.name = auth["info"]["name"]
	      user.email = auth["info"]["email"]
	      user.username = auth["info"]["nickname"]
	    end
	end

	#this code will pull users avatars from Github

	def avatar
		"https://avatars2.githubusercontent.com/u/#{self.uid}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
 
  private
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create     
		auth = request.env["omniauth.auth"]     
		user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)     
		session[:user_id] = user.id     
		redirect_to root_url, :notice => "Signed in!"
	end
 
	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Signed out!"
	end
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end

  def profile 
  	@user = User.find(params[:id])
  end

  def repository 
  	@user = User.all.sample

  	if @user.uid == current_user.uid
  		until @user.uid != current_user.uid
  			@user = User.all.sample
  		end
  	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FMyC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="user-widget">
	<% if current_user %>
		Welcome <strong><%= current_user.name %> <%= current_user.email %> <%= current_user.username %></strong>!
		<%= link_to "Sign Out", signout_path, id: "sign_out" %>
		<br>
		<%= image_tag current_user.avatar %>
	<% else %>
		<%= link_to "Sign in with Github", "/auth/github", id: "sign_in" %>
	<% end %>

</div>

app/views/users/profile.html.erb
<h1>This is the user profile page!</h1>

<%= image_tag @user.avatar %>

app/views/users/repository.html.erb
<h1>Forkable?</h1>

<div><%= @user.name %></div>

<div><%= image_tag @user.avatar %></div>


<%= image_tag current_user.avatar %>

<%= link_to 'Git Checkout', profile_path(@user) %>

<%= link_to 'Git Reset', repository_path %>